insertion_sort : insertion_sort.c
		gcc -Wall -Werror -g -o insertion_sort insertion_sort.c

run :
		./insertion_sort < input.txt > output.txt

run10000 :
		./insertion_sort < ../input10000.txt > ../output10000.txt