selection_sort : selection_sort.c
		gcc -Wall -Werror -g -o selection_sort selection_sort.c

run :
		./selection_sort < input.txt > output.txt

run10000 :
		./selection_sort < ../input10000.txt > ../output10000.txt